TOSIT-IO/tdp-observability

playbooks/grafana_server_config.yml
playbooks/grafana_server_init.yml
playbooks/grafana_server_install.yml
playbooks/grafana_server_restart.yml
playbooks/grafana_server_start.yml
playbooks/grafana_server_stop.yml
playbooks/meta/all.yml
playbooks/meta/all_per_service.yml
playbooks/meta/grafana.yml
playbooks/meta/prometheus.yml
playbooks/prometheus_server_config.yml
playbooks/prometheus_server_install.yml
playbooks/prometheus_server_restart.yml
playbooks/prometheus_server_start.yml
playbooks/prometheus_server_stop.yml

feat: add meta playbooks

---

roles/prometheus/server/tasks/config.yml

fix(prometheus): add owner, group, and mode for file_sd targets files

---

playbooks/exporter_node_install.yml
playbooks/exporter_node_restart.yml
playbooks/exporter_node_start.yml
playbooks/exporter_node_status.yml
playbooks/exporter_node_stop.yml
playbooks/meta/all.yml
playbooks/meta/all_per_service.yml
playbooks/meta/exporter.yml
roles/exporter/node/handlers
roles/exporter/node/tasks/install.yml
roles/exporter/node/tasks/restart.yml
roles/exporter/node/tasks/start.yml
roles/exporter/node/tasks/status.yml
roles/exporter/node/tasks/stop.yml
roles/exporter/node/templates/node-exporter.service.j2
roles/exporter/node/templates/tmpfiles-node-exporter.conf.j2
tdp_lib_dag/exporter.yml
tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

feat(exporter): add node exporter

---

playbooks/exporter_postgres_install.yml
playbooks/exporter_postgres_restart.yml
playbooks/exporter_postgres_start.yml
playbooks/exporter_postgres_status.yml
playbooks/exporter_postgres_stop.yml
playbooks/meta/all.yml
playbooks/meta/exporter.yml
roles/exporter/postgres/handlers/main.yml
roles/exporter/postgres/tasks/install.yml
roles/exporter/postgres/tasks/restart.yml
roles/exporter/postgres/tasks/start.yml
roles/exporter/postgres/tasks/status.yml
roles/exporter/postgres/tasks/stop.yml
roles/exporter/postgres/templates/postgres-exporter.env.j2
roles/exporter/postgres/templates/postgres-exporter.logrotate.j2
roles/exporter/postgres/templates/postgres-exporter.service.j2
tdp_lib_dag/exporter.yml
tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/prometheus/prometheus.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
topology.ini

exporter: add postgres_exporter

---

roles/exporter/node/tasks/install.yml
roles/loki/promtail/tasks/install.yml
roles/loki/server/tasks/install.yml
roles/prometheus/server/tasks/install.yml

Add variables for "source" and "target" binaries directories

---

tdp_vars_defaults/prometheus/prometheus.yml

Prometheus: fix error unable lookup name template string & exporter_node target missing

---

roles/grafana/server/handlers/main.yml
roles/grafana/server/tasks/install.yml
roles/grafana/server/templates/grafana-server.service.j2
roles/grafana/server/templates/grafana-server.sysconfig.j2
tdp_vars_defaults/grafana/grafana.yml

grafana: add air-gap installation

---

galaxy.yml

fix: change namespace to tosit and name to tdp_observability

---

README.md
ROLES.md
playbooks/prometheus_server_config.yml
playbooks/prometheus_server_install.yml
playbooks/prometheus_server_restart.yml
playbooks/prometheus_server_start.yml
playbooks/prometheus_server_stop.yml
requirements.yml
roles/prometheus/server/handlers/main.yml
roles/prometheus/server/tasks/config.yml
roles/prometheus/server/tasks/config_set_web_config.yml
roles/prometheus/server/tasks/configure.yml
roles/prometheus/server/tasks/install.yml
roles/prometheus/server/tasks/preflight.yml
roles/prometheus/server/tasks/restart.yml
roles/prometheus/server/tasks/start.yml
roles/prometheus/server/tasks/stop.yml
roles/prometheus/server/templates/alert.rules.j2
roles/prometheus/server/templates/file_sd.yml.j2
roles/prometheus/server/templates/prometheus.service.j2
roles/prometheus/server/templates/prometheus.yml.j2
tdp_vars_defaults/prometheus/prometheus.yml

feat(prometheus-server): develop TOSIT role for prometheus-server

---

roles/loki/promtail/tasks/config_components_loop.yml
roles/loki/promtail/tasks/config_promtail_scrapes.yml
roles/prometheus/server/tasks/config_components_loop.yml
roles/prometheus/server/tasks/config_prometheus_scrapes.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

feat: add labels at every levels of observability_tdp_targets

---

roles/loki/server/tasks/config.yml

Fixes issue 825 of tdp_collection
backup tasks will now be launched by using the following syntax :
~~~
ansible-playbook <playbook.yml> --tags all,backup
~~~

fix: run backup task only when specified

---

roles/exporter/node/tasks/install.yml
roles/exporter/node/templates/node-exporter.logrotate.j2
roles/exporter/node/templates/node-exporter.service.j2
tdp_vars_defaults/exporter/exporter.yml

exporter_node: configure logs in /var/log/node-exporter and logs rotation

---

roles/grafana/server/tasks/configure.yml
roles/grafana/server/templates/tmpfiles.j2
tdp_vars_defaults/grafana/grafana.yml

grafana: change system group and directory permissions

---

tdp_vars_defaults/grafana/grafana.yml

Fixes [tdp_prerequisites #98](https://github.com/TOSIT-IO/tdp-collection-prerequisites/issues/98)

feat(grafana): dynamic database selection for grafana (sqlite/postgres)

---

roles/exporter/postgres/templates/postgres-exporter.service.j2

exporter_postgres: change system group and log files' permissions

---

roles/loki/promtail/tasks/install.yml
roles/loki/promtail/templates/promtail.logrotate.j2
roles/loki/promtail/templates/promtail.service.j2
roles/loki/server/tasks/install.yml
roles/loki/server/templates/loki.logrotate.j2
roles/loki/server/templates/loki.service.j2
tdp_vars_defaults/loki/loki_promtail.yml
tdp_vars_defaults/loki/loki_server.yml

loki: configure server and promtail logs in /var/log and logs rotation

---

roles/prometheus/server/tasks/install.yml
roles/prometheus/server/templates/prometheus.logrotate.j2
roles/prometheus/server/templates/prometheus.service.j2
tdp_vars_defaults/prometheus/prometheus.yml

prometheus: configure logs in /var/log and logs rotation

---

roles/grafana/server/files/dashboards/tdp-general/tdp-logs.v1.json
roles/grafana/server/files/dashboards/tdp-general/tdp-observability-logs.json
tdp_vars_defaults/loki/loki_promtail.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

Fixes #80 
New dashboard for observability logs

feat(grafana): separate log dashboards

---

roles/grafana/server/tasks/dashboards.yml
tdp_vars_defaults/grafana/grafana.yml

feat(grafana): Enable multiple dashboard directories

---

tdp_vars_defaults/grafana/grafana.yml

fix: upgrade to last version of grafana

---

roles/loki/promtail/tasks/config_jobs_loop.yml
roles/prometheus/server/tasks/config_jobs_loop.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

feat(scrapes): conditional jobs, add "enabled" key

---

ROLES.md
playbooks/meta/all.yml
playbooks/meta/prometheus.yml
playbooks/prometheus_alertmanager_config.yml
playbooks/prometheus_alertmanager_install.yml
playbooks/prometheus_alertmanager_restart.yml
playbooks/prometheus_alertmanager_start.yml
playbooks/prometheus_alertmanager_stop.yml
roles/prometheus/alertmanager/handlers/main.yml
roles/prometheus/alertmanager/tasks/config.yml
roles/prometheus/alertmanager/tasks/config_set_web_config.yml
roles/prometheus/alertmanager/tasks/configure.yml
roles/prometheus/alertmanager/tasks/install.yml
roles/prometheus/alertmanager/tasks/preflight.yml
roles/prometheus/alertmanager/tasks/restart.yml
roles/prometheus/alertmanager/tasks/selinux.yml
roles/prometheus/alertmanager/tasks/start.yml
roles/prometheus/alertmanager/tasks/stop.yml
roles/prometheus/alertmanager/templates/alertmanager.env.j2
roles/prometheus/alertmanager/templates/alertmanager.logrotate.j2
roles/prometheus/alertmanager/templates/alertmanager.service.j2
roles/prometheus/alertmanager/templates/alertmanager.yml.j2
roles/prometheus/alertmanager/templates/amtool.yml.j2
roles/prometheus/server/tasks/config.yml
roles/prometheus/server/templates/prometheus.yml.j2
tdp_lib_dag/prometheus.yml
tdp_vars_defaults/prometheus/alertmanager.yml
tdp_vars_defaults/prometheus/prometheus.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
topology.ini

feat: Alertmanager role

---

roles/grafana/server/templates/grafana.ini.j2
tdp_vars_defaults/grafana/grafana.yml

feat(grafana): default bind to 0.0.0.0

---

roles/exporter/node/tasks/install.yml
roles/grafana/server/tasks/install.yml
roles/loki/promtail/tasks/install.yml
roles/loki/server/tasks/install.yml
roles/prometheus/alertmanager/tasks/install.yml
roles/prometheus/server/tasks/install.yml

fix: ansible.builtin.copy dest should specify full filename

---

roles/loki/promtail/tasks/install.yml
tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/loki/loki_promtail.yml

fix: node-exporter group should be "node-exporter"

---

tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/grafana/grafana.yml
tdp_vars_defaults/loki/loki_promtail.yml
tdp_vars_defaults/loki/loki_server.yml
tdp_vars_defaults/prometheus/alertmanager.yml
tdp_vars_defaults/prometheus/prometheus.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

feat: Globalize xxx_root_dir default values

---

roles/grafana/server/tasks/dashboards.yml
roles/loki/promtail/tasks/install.yml
roles/prometheus/server/tasks/config_components_loop.yml
tdp_vars_defaults/exporter/exporter.yml
tdp_vars_defaults/grafana/grafana.yml
tdp_vars_defaults/loki/loki_promtail.yml
tdp_vars_defaults/loki/loki_server.yml
tdp_vars_defaults/prometheus/alertmanager.yml
tdp_vars_defaults/prometheus/prometheus.yml
tdp_vars_defaults/tdp-cluster/tdp-cluster.yml

fix(promtail): generate secondary group list dynamically

---

roles/grafana/server/files/dashboards/tdp-general/tdp-logs.json
roles/grafana/server/files/dashboards/tdp-general/tdp-observability-logs.json

feat: sort logs in ascending order

---

tdp_vars_defaults/loki/loki_promtail.yml

feat(promtail): merge "warn" and "warning" log levels

---

tdp_vars_defaults/firewall/firewall.yml

Fixes https://github.com/TOSIT-IO/tdp-collection-extras/issues/213

feat: add grafana to firewall

---

galaxy.yml

Fixes None
Bump to version `1.0.1`.

feat(versioning): to version 1.0.1

---

playbooks/meta/all.yml
playbooks/meta/exporter.yml

Meta playbooks update following a change in the dag construction logic by tdp-lib.

Update meta playbooks

---

tdp_vars_defaults/exporter/exporter.yml

Fixes #
Upgrade node-exporter to last version

feat: node-exporter 1.9
